apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: guestbook
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: guestbook
    component: frontend
